// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY1QzxtZ1Ci5qX4tIMg3nWYr50m71dJ0Q',
    appId: '1:868113720369:web:367bedff83809d3bd32110',
    messagingSenderId: '868113720369',
    projectId: 'social-media-5da2a',
    authDomain: 'social-media-5da2a.firebaseapp.com',
    databaseURL: 'https://social-media-5da2a-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-5da2a.appspot.com',
    measurementId: 'G-532X2GYNEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc8xb89-ddqXQ6xQXpqA4eFPHGzow4sBI',
    appId: '1:868113720369:android:8e47abf70bc39024d32110',
    messagingSenderId: '868113720369',
    projectId: 'social-media-5da2a',
    databaseURL: 'https://social-media-5da2a-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-5da2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8EGXpQUCSLo4fjqBTQGMn1friClaxZI',
    appId: '1:868113720369:ios:fb2eaad195107c07d32110',
    messagingSenderId: '868113720369',
    projectId: 'social-media-5da2a',
    databaseURL: 'https://social-media-5da2a-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-5da2a.appspot.com',
    iosClientId: '868113720369-mdcfeq2acftei61m1b2jc0i4us11qm13.apps.googleusercontent.com',
    iosBundleId: 'com.example.connect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK8EGXpQUCSLo4fjqBTQGMn1friClaxZI',
    appId: '1:868113720369:ios:fb2eaad195107c07d32110',
    messagingSenderId: '868113720369',
    projectId: 'social-media-5da2a',
    databaseURL: 'https://social-media-5da2a-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-5da2a.appspot.com',
    iosClientId: '868113720369-mdcfeq2acftei61m1b2jc0i4us11qm13.apps.googleusercontent.com',
    iosBundleId: 'com.example.connect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY1QzxtZ1Ci5qX4tIMg3nWYr50m71dJ0Q',
    appId: '1:868113720369:web:8084fe0784bd4312d32110',
    messagingSenderId: '868113720369',
    projectId: 'social-media-5da2a',
    authDomain: 'social-media-5da2a.firebaseapp.com',
    databaseURL: 'https://social-media-5da2a-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-5da2a.appspot.com',
    measurementId: 'G-27M4SNCRW7',
  );
}
